redis:
  port : 6379
  host: "127.0.0.1"
mysql:
  host: "172.20.10.152"
  userName: "root"
  password: "nacos"
  dbname: "test_go"
  port: 30072


server:
  port: "8080"
  mode: "debug"    #debug模式，release模式，test测试模式
  host: "0.0.0.0"  # 本机地址
  ReadTimeout: 60
  WriteTimeout: 60